### ISSUE TITLE
Request generic args default to `unknown`

### ISSUE THREAD

**Issue by tpluscode** [tranvansang/middleware-async#29]
With the latest version (1.3.2) the defaults for asyncMiddleware, and by extension the `req/res` arguments of passed function are all `unknown`

Effectively, it looks like this

```typescript
import asyncMiddleware from 'middleware-async'

export default asyncMiddleware((req: Request<unknown, unknown, unknown, unknown>, res: Response<unknown, unknown>) => {
  // ...
})
```

Because of all the unknowns, the `req` and `res` are problematic when trying to access their properties or pass them around.

For example, if I try to cast `req` to `Request` I get the error 

> TS2345: Argument of type 'Request<unknown, unknown, unknown, unknown, unknown>' is not assignable to parameter of type 'Request<ParamsDictionary, any, any, ParsedQs, Record<string, any>>'.

Why did this change? It would be nice if the default values for the generic args reflected the default set in [express types themselves]( https://github.com/DefinitelyTyped/DefinitelyTyped/blob/5c969819f9f14f99c8966867743c3d1947fbbf18/types/express-serve-static-core/index.d.ts#L60-L73)

**Comment by tranvansang** [comment]
@tpluscode somehow I didn't get a notification email for the issue.

I have improved the typing and released version 1.3.5

**Comment by tpluscode** [comment]
Ah, indeed, sorry about that.

I'm actually really weirded out by the change that was made

```diff
-exports["default"] = exports.asyncMiddleware;
+exports.default = exports.asyncMiddleware;
```

🤯

**Comment by tranvansang** [comment]
https://github.com/tranvansang/middleware-async/compare/v1.3.2...v1.3.5

it changed alot
