### ISSUE TITLE
Inaccurate TS declaration

### ISSUE THREAD

**Issue by tpluscode** [tranvansang/middleware-async#38]
When importing `middleware-async` from an ES module, one can easily try an incorrect import 

```js
import asyncMiddleware from 'middleware-async'
```

It will subsequently fail because that is not a function albeit being declared like that in the `.d.ts`. I believe the correct would be call it as `asyncMiddleware.default`.

In any case, I would see if the generated type declaration can be improved

**Comment by tranvansang** [comment]
@tpluscode 

es6 support was added to version 1.3.4 (already released).

Now you can use both `import asyncMiddleware from 'middleware-async'` or `import {asyncMiddleware} from 'middleware-async'`

Please try the new version and feel free to re-open the issue if it is not fixed.
